name: "Hello world workflow"

# Controls when the action will run. Triggers the workflow on push done to master or production branch
on:
    push:
        branches:
            - main
            - production

jobs:
    hello_world:
        runs-on: ubuntu-latest   # This tells what type of running environment will be setup on the machine where this wotkflow will be executed. This machines are called runners
        steps:
            - name: "Print hello world"
              run: echo "Hello World" 

                                     
                                                       
                                                        
             